### ISSUE TITLE
AsyncApiSpec

### ISSUE THREAD

**Issue by JanEggers** [RSuter/SigSpec#11]
I think the generated document should have the format of https://www.asyncapi.com

**Comment by RSuter** [comment]
I’m wondering whether this really matches without “hacks” - i dont know asyncapi much, but it seems it is for async messages. How would callbacks be described?

**Comment by JanEggers** [comment]
hmm nevermind

**Comment by RSuter** [comment]
It’s fine and should be discussed - i think i heard this before 🙂
